### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#10]
- [x] site logo, size 550 x 88 px (preferable in PSD, with white letters for current theme scheme)
- [x] project by logos (preferable in PSD or Hi-Res PNG) - IME, CfC, any other?
- [ ] project supporters / partners (any institutional support, who?) (preferable in PSD or Hi-Res PNG)

**Comment by MarinB** [comment]
Pozdrav Miroslave,

za trenutnu shemu teme za sajt mislim da odgovara ovakav logo.

Što misliš hoće li odgovarati?

![logo_reklamacije](https://cloud.githubusercontent.com/assets/18548196/15160251/0f997968-16f9-11e6-81a6-4c1a43c7ecff.png)

**Comment by schlos** [comment]
@MarinB 
Kako ti ovo izgleda:
https://qsnapnet.com/snaps/zvi5qp3k5yjk052

Ako ti vizualno izgleda OK, samo mi potvrdi da stavim [novi u template](https://github.com/codeforcroatia/reklamacijenet-theme/blob/master/assets/images/logo%402.png).

Trenutno sam IME stavio kao text u logo (u headeru stranice), pa ako imas neki logo i za IME, javi mi da i to zamjenim.

**Comment by MarinB** [comment]
Pozdrav,

ne sviđa mi se boja koja je bila. Stavio sam u bijelu pa probajmo ovako. Ako treba možemo još povećati, što misliš?
![logo_reklamacije2](https://cloud.githubusercontent.com/assets/18548196/15222817/b2e2f846-1871-11e6-9867-74ce73a82be3.png)

Za IME javim sutra što ćemo.

**Comment by schlos** [comment]
@MarinB 
Kako sada izgleda:
https://qsnapnet.com/snaps/yswgdpbfp2l6jem

Da pls, velicina za zaslone visoke rezolucije (retina) treba biti 550 x 88 px. Mozes li mi poslati tocno u toj rezoluciji da ja ne moram rezati/resajzati pa da ne gubi na kvaliteti?

**Comment by MarinB** [comment]
Mislim da je to bolje sada.

Šaljem povećani logo u točnim dimenzijama pa probajmo.

Što se tiče znaka za IME, mislim da nema potrebe. Ovo je poprilično dobro,
što misliš?

Na raspolaganju sam.

LP
Marin

2016-05-13 0:14 GMT+02:00 Miroslav notifications@github.com:

**Comment by schlos** [comment]
Meni isto izgleda OK. Cekam onda da mi posaljes logo u vecim / tocnim dimenzijama. Ako mozes do sub navecer, super tako da mogu pushati novi kod.

Za IME, super, sto se mene tice moze ostati pa se azurira kada i ako sredite neki drugaciji logo.

@reklamacije IvanB, postoje li neki partneri na projektu (osim Code for Croatia) koje treba ukljuciti / prikazati kao "Partneri projekta", ili Institucionalna podrska ili nesto trece?

**Comment by MarinB** [comment]
Aha, mislio sam da je stigao i povećani logo. Šaljem ovdje pa probajmo.
![logo_reknet_550x88](https://cloud.githubusercontent.com/assets/18548196/15266891/c91b36ea-19b2-11e6-8c2d-d86027d53add.png)

**Comment by schlos** [comment]
Odlicno, stavljam u temu.

Mozes li kreirati i sliku za drustvene mreze?
Ovo je trenutna:
https://raw.githubusercontent.com/codeforcroatia/reklamacijenet-theme/master/assets/images/logo-opengraph.png
- to je "opengraph" logo za drustvene mreze, ucitava se kada link stranice sheras na Facebook, Twitter itd.

Slozi nesto na tragu onog loga koji si napravio s barkodom ali u dimenzijama ove slike s linka (samo da ne bude bijelo inace se na bijeloj pozadini nece vidjeti.

**Comment by MarinB** [comment]
Pozdrav,

jesi ovako nešto mislio?

Ako je dobro (dimenzije, boja i ako se vidi dobro) možemo s time.

Što misliš?

Javi ako što treba!

Pozz
Marin

2016-05-14 9:17 GMT+02:00 Miroslav notifications@github.com:

**Comment by schlos** [comment]
@MarinB Nisam nista zaprimio u attachmentu.

**Comment by MarinB** [comment]
Šaljem...
![openlogo](https://cloud.githubusercontent.com/assets/18548196/15273208/e27bd9f2-1a91-11e6-9942-7878e352fff6.png)

**Comment by schlos** [comment]
Odlicno je!

**Comment by schlos** [comment]
@reklamacije IvanB, postoje li neki partneri na projektu (osim Code for Croatia) koje treba ukljuciti / prikazati kao "Partneri projekta", ili Institucionalna podrska ili nesto trece?

**Comment by reklamacije** [comment]
Ne, samo IME i Code for Croatia, Open.hr itd. - možda kasnije dođu neke udruge za zaštitu potrošača i sl. ali s njima planiramo razgovarati tek tijekom ljeta ...
