### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#11]
Share replacement image for background (full size, hi-res).

Current image:
https://qsnapnet.com/snaps/iymswzq4fk98jjo

**Comment by schlos** [comment]
@reklamacije IvanB, mozes li pogledati ovo?

**Comment by schlos** [comment]
Nema odgovora pa zatvaram bez promjene slike.

**Comment by reklamacije** [comment]
Sorry za ovo bez odgovora. Možda ova. Ne mogu naći ništa bolje - a možda ako se spoji sa natpisom  koji ima barcode crte možda dobije neki smisao .... jači!

Ovo je link na sliku - horizontalna - velika
https://pixabay.com/en/city-urbanization-tree-aesthetic-990843/

**Comment by schlos** [comment]
@reklamacije Pozz Ivan,
Kako ti ovo izgleda? Preview s novom slikom u pozadini:
https://qsnapnet.com/snaps/00uav1nniea02j4

IMHO, malo je presvjetla slika i ne vidi se dobro text na slici.

**Comment by schlos** [comment]
Shopping kolica:
https://pixabay.com/en/shopping-cart-shopping-supermarket-1275480/

**Comment by schlos** [comment]
Placanje:
https://pixabay.com/en/money-card-business-credit-card-256314/

**Comment by schlos** [comment]
IvanB se odlucio za shopping kolica:
https://pixabay.com/en/shopping-cart-shopping-supermarket-1275480/

**Comment by schlos** [comment]
Assignam na sebe za daljnji rad na ovom.

**Comment by reklamacije** [comment]
jesam, shopping  kolica su  najbolja

**Comment by schlos** [comment]
Updejtano. Stavljeno na test. zatvaram ovaj ticket.
