### ISSUE TITLE
Twitter Widget ID for account "reklamacijenet"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#13]
Get Twitter Widget ID following instructions at https://twitter.com/settings/widgets

```
# Set the widget_id to get the Twitter sidebar on the blog page.
# To get one https://twitter.com/settings/widgets
#
# TWITTER_WIDGET_ID - String widget ID (default: false)
#
# Examples:
#
#   TWITTER_WIDGET_ID: '833549204689320031'
#
# ---
```

**Comment by schlos** [comment]
`<a class="twitter-timeline" href="https://twitter.com/reklamacijenet" data-widget-id="724267021916082176">Tweets by @reklamacijenet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>`

**Comment by reklamacije** [comment]
Ovo treba stranica biti gotova? Je l tak? Da se stavi widget?

**Comment by schlos** [comment]
Ne razumijem pitanje. Dobio sam potrebno, i biti ce postavljeno na Alaveteli vas Twitter ID. On sluzi za sheranje sadrzaja s Alaveteli stranice (Tweet about this...). Nema nikakve izravne veze s WP portalom.

**Comment by schlos** [comment]
724267021916082176
