### ISSUE TITLE
Dedicated Analytics code for Alaveteli site

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#15]
Get dedicated Google Analytics code for Alaveteli site.

```
# Adding a value here will enable Google Analytics on all non-admin pages for
# non-admin users.
#
# GA_CODE - String (default: nil)
#
# Examples:
#
#   GA_CODE: 'AB-8222142-14'
#
# ---
GA_CODE: ''
```

**Comment by schlos** [comment]
@reklamacije IvanB, mozes li mi poslati novi Google Analytics za koristenje na poddomeni podnesi.reklamacije.net?

**Comment by reklamacije** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77704277-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by reklamacije** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77704277-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by reklamacije** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77704277-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by reklamacije** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-77704277-1', 'auto');
  ga('send', 'pageview');
</script>

**Comment by reklamacije** [comment]
Je li ovaj google analytics kod dobar?

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-77704277-1', 'auto');
  ga('send', 'pageview');
 
</script>

**Comment by schlos** [comment]
Koji kod? @reklamacije

**Comment by reklamacije** [comment]
za google analytics što sam poslao mailom. ali tek sada vidim da je je ovo beta testing faza ....

**Comment by schlos** [comment]
Je, dobar je: UA-77704277-1

**Comment by schlos** [comment]
Done (reklamacije.net GA code added).
