### ISSUE TITLE
Prepare initial list of companies

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#2]

**Comment by schlos** [comment]
@reklamacije initial list include:

- **Popis tijela javne vlasti** ([link](http://data.gov.hr/dataset/azurirani-popis-tijela-javne-vlasti)) ~ 6.000 with 80% addresses
- **Registar poslovnih subjekata** ([link](https://app.box.com/s/jfusqs99q07w2tg9slzwtesnbgl3kbv2)) ~ 65.000 without addresses - they have to be added manually as per need basis

Categories:

- template **Kategorije pravnih osoba** ([GDocs link](https://docs.google.com/spreadsheets/d/1S6C3T-XJ3HpdVvCKFCcgsfKkKbS5vQAt7r1aRgi4Kic/edit?usp=sharing))
- categorization based on Zakon o zastiti potrosaca - Javne usluge koje se pruzaju potrosacima ([Cadial link](http://www.digured.hr/cadial/searchdoc.php?action=search&lang=hr&query=zakon+o+zastiti+potrosaca+41%2F14&searchTitle=on&validacts=on&resultdetails=basic&filteracttype=all&filterfields=all&filtereuchapter=all&resultlimitnum=10&bid=RamJlj6oF73BfShWlhovmA%3d%3d&annotate=off))

**Comment by schlos** [comment]
@reklamacije 

Initial list include:

• ​**Popis tijela javne vlasti_​_ ([link](http://data.gov.hr/dataset/azurirani-popis-tijela-javne-vlasti)) ~ 6.000 with 80% addresses
• ​**Registar poslovnih subjekata_​_ ([link](https://app.box.com/s/jfusqs99q07w2tg9slzwtesnbgl3kbv2)) ~ 65.000 without addresses - they have to be added manually as per need basis

Categories:

• template ​**Kategorije pravnih osoba**​ ([GDocs link](https://docs.google.com/spreadsheets/d/1S6C3T-XJ3HpdVvCKFCcgsfKkKbS5vQAt7r1aRgi4Kic/edit?usp=sharing))
• categorization based on Zakon o zastiti potrosaca - **Javne usluge koje se pruzaju potrosacima** ([Cadial link](http://www.digured.hr/cadial/searchdoc.php?action=search&lang=hr&query=zakon+o+zastiti+potrosaca+41%2F14&searchTitle=on&validacts=on&resultdetails=basic&filteracttype=all&filterfields=all&filtereuchapter=all&resultlimitnum=10&bid=RamJlj6oF73BfShWlhovmA%3d%3d&annotate=off))

**Comment by reklamacije** [comment]
Ok.

**Comment by reklamacije** [comment]
Pripremio sam materijale. Bolje govoreći skinuo ove koje si ti skinuo, unijeti ću ih nekoliko da vidim kako sve funkcionira i da napravim sistem unosa, a onda prepustiti volonterima i raditi kontrolu. Unosa i testiranja ...

**Comment by schlos** [comment]
Ne trebas rucno unositi svih 65.000. Importirati cu ih ja. Samo mi pripremi xls prema templateu koji sam ti poslao/sherao na Google Driveu

**Comment by reklamacije** [comment]
Ovo ne znam može li nam Ivan K. išta pomoći. Ovo što nudi više manje i nije nam od velikog značaja pa predlažem da unesemo po prvobitnoj ideje - 1. razina nkd, bez kontakata a kontakte onda krenemo unositi ...

**Comment by schlos** [comment]
Done.
