### ISSUE TITLE
Refactor translations for reklamacije

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#3]
Adapt translations accordingly

Zakon o zastiti potrosaca http://www.digured.hr/cadial/searchdoc.php?action=search&lang=hr&query=zakon+o+zastiti+potrosaca+41%2F14&searchTitle=on&validacts=on&resultdetails=basic&filteracttype=all&filterfields=all&filtereuchapter=all&resultlimitnum=10&bid=RamJlj6oF73BfShWlhovmA%3d%3d&annotate=off

**Comment by schlos** [comment]
Partially done (already uploaded on test)

**Comment by schlos** [comment]
**Upute kako dodati sliku u prigovor:**

Dodati u sidebar gdje je opis prilikom pisanja nove reklamacije (vidi screenshot trenutne recenice: https://qsnapnet.com/snaps/5ix0sqywce17zao).

Napisati novu recenicu u kojoj bismo rekli podnositelju da _moze koristiti servis https://imgsafe.org/ da uplodaju sliku / dokaz i link na uplodanu sliku ubace u opis reklamacije._

cc @reklamacije dostavite ispravljenu ovu recenicu za upute za upload slike

**Comment by reklamacije** [comment]
Da. Staviti ćemo kratke upute kako da stave link. A neke reklamacije možemo „pokupiti“ i objaviti sa slikom na main portalu reklamacije.net – bumo vidjeli.

**Comment by schlos** [comment]
Hi Ivan!

Mozes li pojasniti malo detaljnije dio "neke reklamacije možemo „pokupiti“ i objaviti sa slikom na main portalu reklamacije.net". Kako bi to funkcioniralo? Koji je workflow za to?

**Comment by schlos** [comment]
Jesi li mislio nesto poput ovog WP plugin-a staviti na glavni WP sajt:
https://wordpress.org/plugins/closify-maestro-image-uploader-gallery-builder/

Izbor nacina externog uploda slika ne utjece previse na opisni text koji ce kao uputa stajati na Alaveteli portalu. Jedno i drugo je neki vanjski link koji omogucuje korisniku da uploda sliku i stavi link u tekst reklamacije. Tekst za taj proces mozemo vec sada staviti a link na lokaciju gdje uplodati sliku se uvijek kasnije moze izmjeniti.

**Comment by reklamacije** [comment]
Pa ideja je da se na main portalu pokazuju i random (naslovi) reklamacija koju objavili građani na podnesi-reklamacije.net. Da se portali bolje integriraju. Ali sam mislio kada sve zaživi (i uredništvo i novinari na main portalu) da se i „ručno“ prenesu određeni tekstovi (uz dopuštenje autora) s podnesi-reklamacije.net na main portal. A u tom prijenosu se u tekst može ukombinirati i slika koju je prije toga korisnik stavio na neki od image servisa. Ako uredništvo portala vidi da je nešto „vruće“ da kontaktira autora i uz njegovo dopuštenje stavi njegov tekst kao vijest na main portal te slikovne materijale također ukombinira u tekst. Dakle, workflow je „ručno“ :D

**Comment by reklamacije** [comment]
Jesam. Ali sve te stvari oko WP bi htio popričati s čovjekom koji će raditi portal. Samo čekam da krešo kaže jesmo li završili potragu ili tražimo dalje. Navodno je našao nekoga. Onda bi se našli s njim i vjerujem da ta osoba zna puno više od mene koju su sve mogućnosti današnjeg WP i što sve možemo staviti i kako najbolje spojiti  ovaj dio koji stvaraju građani, firme, javne službe i ovaj dio koji je stvaraju novinari.  Samo da krešo javi pa ću znati što je sve moguće .... ali da i takve opcije, poput gallery buildera, su dobrodošle ...

**Comment by schlos** [comment]
Sada mi je jasno okvirno sto si zelio reci. Malo smo otisli offtopic, jer je naslov ovog ticketa izmjene u prijevodima na Alaveteli portalu, a moj komentar se odnosio na dodatno objasnjenje korisniku prilikom pisanja novog komentara da mu se objasni za dodavanje slike u prigovor koji salje. To je ono sto smo pricali na Slacku.

Molim te, mozes li mi poslati ispravljenu verziju texta (jedna kratka recenica) koja bi to objasnjavala?
(pogledaj moj komentar na linku https://github.com/codeforcroatia/Podnesi-Reklamacije.net/issues/3#issuecomment-213732451)

**Comment by reklamacije** [comment]
Je, malo offtopic J

Evo teksta

Opišite konkretan slučaj te navedite detalje poput datuma, lokacije, opišite proizvod ili uslugu, broj računa ili dokumenta i slično. Ukoliko želite priložiti slike predlažemo da iskoriste neki od servisa za podizanje slika (npr.www.imgsafe.org) i link sa slikom dodajte u tekst.

**Comment by schlos** [comment]
Obavljeno - zatvaram.
