### ISSUE TITLE
Assembly help pages

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/Reklamacije.net#9]
Current help pages includes:
- Introduction text / O projektu
- Making appeals / Podnosenje prigovora
- Your privacy / Politika privatnosti
- FOI officers / Stranica za primatelje prigovora
- About software / O ovom softveru (ostaje kako je - nepromjenjeno)
- Credits / Zahvale
- Programmers API / API za programere (ostaje kako je - nepromjenjeno)
- Help us / Pomozite nam
- Advanced search / Napredna pretraga (ostaje kako je - nepromjenjeno)
- Contact us / Kontaktirajte nas
- Unhappy / Nezadovoljni ste odgovorom?

Link: http://podnesi-test.reklamacije.net/help/about

Potrebno sastaviti sljedece stranice:
- [x] Uvodni tekst o projektu Reklamacije.net, dio za odnosenje prigovora (svrha projekta, opcenito opisati zakonsku regulativu kako potrosac moze dostaviti prigovor trgovcu koristenjem ove stranice ili prigovor na eticki odnos sluzbenika u javnim sluzbama ili prijava korupcije, itd..)
- [x] Podnosenje prigovora, zalidbeni proces iz korisnicke perspektive, cesta pitanja i odgovori (moze se opisati procedura za Zakon o zastiti potrosaca, Zakon o drzavnim sluzbenicima itd), i.e. http://potrosac.mingo.hr/hr/potrosac/clanak.php?id=12489 http://potrosac.mingo.hr/hr/potrosac/clanak.php?id=12671
  https://www.gov.hr/moja-uprava/pravna-drzava-i-sigurnost/prijava-i-pohvala-drzavnih-sluzbenika/prijava-neeticnog-ponasanja-drzavnog-sluzbenika/1578
  http://www.jutarnji.hr/drzavni-sluzbenik-vise-nije-zasticen--ako-je-bezobrazan-i-nekorektan-mozete-ga-prijaviti/939994/
  https://gov.hr/moja-uprava/pravna-drzava-i-sigurnost/prevencija-i-prijava-kaznenog-djela/prijava-korupcije/1702
  https://pravosudje.gov.hr/istaknute-teme/antikorupcija-6154/6154
  https://pravosudje.gov.hr/istaknute-teme/antikorupcija/kome-prijaviti/6176
  http://www.dorh.hr/KontaktiSGradanima
  http://www.transparency.hr/hr/prijavi-korupciju
- [x] Politika privatnosti stranice
- [x] Stranica za primatelje prigovora, cesta pitanja i odgovori primatelja prigovora
- [x] Zahvale, navesti osobe kojima je potrebno zahvaliti za sudjelovanej na prohektu, popis volontera, moguce i naknadno nadodati potrebne dijelove zahvala
- [x] Pomozite nam, odgovor na pitanje - mogu li i ja pomoci? kako?
- [x] Kontaktirajte nas, opisite tko smo mi i sto nas mozete pitati, kako kontaktirati (na email ili na neki drugi link?)
- [x] Nezadovoljni ste odgovorom?, opisite na ovoj stranici postupak zalbe na odgovor reklamacije ako je kupac/korisnik nezadovoljan. Trenutno je to ova stranica (http://podnesi-test.reklamacije.net/help/unhappy/naslov_testnog_zahtjeva). Primjer uputa za zalbu na reklamaciju: http://www.24sata.hr/pametnakuna/saznajte-na-koje-nacine-se-mozete-zaliti-hep-u-272335

**Comment by schlos** [comment]
Review drafta stranica by Dora - In progress:
- Help - O PROJEKTU
- Help - PODNOŠENJE PRIGOVORA
- Help - politika privatnosti stranice

@reklamacije IvanB, hoces li pogledati komentare koje sam ostavio na Google Docs?

**Comment by reklamacije** [comment]
Doraaaa :)

**Comment by reklamacije** [comment]
Poslao mailom ...

**Comment by schlos** [comment]
Nedostaje jos:
- Unhappy stranica - Nezadovoljni ste odgovorom?, opisite na ovoj stranici postupak zalbe na odgovor reklamacije ako je kupac/korisnik nezadovoljan. Trenutno je to ova stranica (http://podnesi-test.reklamacije.net/help/unhappy/naslov_testnog_zahtjeva). Primjer uputa za zalbu na reklamaciju: http://www.24sata.hr/pametnakuna/saznajte-na-koje-nacine-se-mozete-zaliti-hep-u-272335

**Comment by reklamacije** [comment]
Nisam našao  neke greške  na help stranicama - osim što neke nisu prevedene s engleskog i linkovi vuku  na stranice na engleskom 

http://podnesi-test.reklamacije.net/help/contact

http://podnesi-test.reklamacije.net/help/api

**Comment by schlos** [comment]
@reklamacije Ivan, mozes li mi dostaviti i text za tu stranicu "kontaktirajte nas"
- Kontaktirajte nas, opisite tko smo mi i sto nas mozete pitati, kako kontaktirati (na email ili na neki drugi link?)

Pogledaj text na:
http://podnesi-test.reklamacije.net/help/contact

**Comment by reklamacije** [comment]
Poslao sam mailom jer ne hvata ODS file

**Comment by schlos** [comment]
@reklamacije Nisam nista primio. Mozes li mi ponovno poslati?

**Comment by schlos** [comment]
Help je updejtan. Moze se pogledati na testnom portalu. Zatvaram ovaj ticket.
